language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3.0
cache: bundler
sudo: false
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
script: bundle exec rake
matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.0
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_5.0.gemfile
      rvm: 2.2
