language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
cache: bundler
sudo: false
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
script: bundle exec rake
matrix:
  fast_finish: true
  exclude:
  - gemfile: gemfiles/rails_5.0.gemfile
    rvm: 2.2
  - gemfile: gemfiles/rails_5.1.gemfile
    rvm: 2.2
